os:
  - linux
  - osx
language: node_js
node_js:
  - "10.14"
  - "10"
  - "12"
  - "13"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn install --frozen-lockfile
  - yarn build
cache: yarn
after_success:
  - yarn codecov --disable=gcov -F unittests
  - yarn tap test/*.test.ts --coverage-report=text-lcov | yarn codecov -l --disable=gcov -F integration
